version: '3'
services:
  api:
    build: ./api
    container_name: "api"
    ports:
      - "8080:80"
    volumes:
      - "./api/volume:/tmp"
    tty: true
    stdin_open: true
  target:
    build: ./target
    container_name: "target"
    ports:
      - "9999:9999"
    volumes:
      - "./target/volume:/tmp"
    tty: true
    stdin_open: true

networks:
  default:
    external:
      name: br0
