version: '3'
services:
  wakeonlan:
    build: ./wol
    container_name: wakeonlan
    ports:
      - "8080:8000"
    volumes:
      - "./api/volume:/tmp"
    tty: true
    stdin_open: true
networks:
  default:
    external:
      name: br0
